blank_issues_enabled: true
contact_links:
  - name: There is an issue with presets or osm tagging recommendations
    url: https://github.com/openstreetmap/id-tagging-schema/issues
    about: Please share your feedback in the id-tagging-schema repository.
  - name: There is an issue with brand icons or brand tagging recommendations.
    url: https://github.com/osmlab/name-suggestion-index/issues
    about: Please create a feature request in the name-suggestion-index repository.
